import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/providers/theme-provider'

import SupabaseProvider from '@/components/providers/supabase-provider'
import ToastProvider from '@/components/providers/toastprovider'
import { ModalProvider } from '@/components/providers/moda-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NotesJunction',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        media: '(prefers-color-scheme:light)',
        url: '/logo-dark.svg',
        href: '/logo-dark.svg',
      },
      {
        media: '(prefers-color-scheme:dark)',
        url: '/logo.svg',
        href: '/logo.svg',
      },
    ],
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <SupabaseProvider>
          <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
            <ToastProvider/>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
                storageKey="notes-key"
              >
                <ModalProvider/>
                {children}
              </ThemeProvider>
            </body>
          </html>
        </SupabaseProvider>
  )
}
